const axios = require('axios');
const { prisma } = require('../config/database');

/**
 * Jira Service
 * Handles interaction with Atlassian Jira Cloud REST API v3
 */
class JiraService {
  /**
   * Create a Jira issue from an EchoNote action item
   * @param {Object} user - User object with Jira settings
   * @param {Object} actionItem - ActionItem object
   * @returns {Promise<Object>} Created issue details
   */
  async createIssue(user, actionItem) {
    if (!user.jiraDomain || !user.jiraEmail || !user.jiraApiToken || !user.jiraProjectKey) {
      throw new Error('Jira configuration incomplete for this user');
    }

    const domain = user.jiraDomain.trim().replace(/\/$/, '').replace(/^https?:\/\//, '');
    const projectKey = user.jiraProjectKey.trim().toUpperCase();
    const url = `https://${domain}/rest/api/2/issue`; // Using v2 for plain text support
    const auth = Buffer.from(`${user.jiraEmail.trim()}:${user.jiraApiToken.trim()}`).toString('base64');

    const summary = (actionItem.task || 'EchoNote Action Item').substring(0, 255);
    const meetingTitle = actionItem.meeting?.title || 'Untitled Meeting';
    
    // Construct plain text description for v2
    let description = `This task was automatically generated by EchoNote.\n\n`;
    description += `MEETING: ${meetingTitle}\n`;
    if (actionItem.sourceQuote) {
      description += `TRANSCRIPT CONTEXT:\n"${actionItem.sourceQuote}"\n\n`;
    }
    description += `View meeting details in EchoNote: ${process.env.FRONTEND_URL || 'http://localhost:3000'}/meeting/${actionItem.meetingId}`;

    const body = {
      fields: {
        project: { key: projectKey },
        summary: summary,
        description: description,
        issuetype: { name: 'Task' }
      }
    };

    // Add Due Date if valid
    if (actionItem.deadline) {
      console.log(`Processing deadline for Jira: "${actionItem.deadline}"`);
      const dateMatch = actionItem.deadline.match(/\d{4}-\d{2}-\d{2}/);
      if (dateMatch) {
        body.fields.duedate = dateMatch[0];
      } else {
        // Try to parse it normally if it's a date string
        try {
          const d = new Date(actionItem.deadline);
          if (!isNaN(d.getTime())) {
            body.fields.duedate = d.toISOString().split('T')[0];
          }
        } catch (e) {
          console.error(`Failed to parse deadline "${actionItem.deadline}":`, e.message);
        }
      }
      if (body.fields.duedate) {
        console.log(`Parsed due date for Jira: ${body.fields.duedate}`);
      }
    }

    // Add priority if it exists and map it
    if (actionItem.priority) {
      body.fields.priority = { name: this.mapPriority(actionItem.priority) };
    }

    // Add labels
    body.fields.labels = ['EchoNote'];
    
    // Add meeting title as label (sanitized)
    if (meetingTitle) {
      const titleLabel = meetingTitle
        .replace(/[^\w\s-]/g, '') // Remove special chars
        .replace(/\s+/g, '-')     // Replace spaces with hyphens
        .substring(0, 50);        // Limit length
      if (titleLabel) body.fields.labels.push(titleLabel);
    }
    
    // Keep meeting ID label for technical reference but make it cleaner
    if (actionItem.meetingId) {
      body.fields.labels.push(`MID-${actionItem.meetingId.substring(0, 8)}`);
    }

    try {
      console.log('Sending request to Jira (API v2):', {
        url,
        project: projectKey,
        summary: summary,
        duedate: body.fields.duedate
      });

      const response = await axios.post(url, body, {
        headers: {
          'Authorization': `Basic ${auth}`,
          'Content-Type': 'application/json',
          'Accept': 'application/json'
        }
      });

      // Update action item with Jira info
      await prisma.actionItem.update({
        where: { id: actionItem.id },
        data: {
          jiraIssueKey: response.data.key,
          jiraIssueId: response.data.id
        }
      });

      return {
        success: true,
        key: response.data.key,
        id: response.data.id,
        url: `https://${domain}/browse/${response.data.key}`
      };
    } catch (error) {
      const errorData = error.response ? error.response.data : null;
      const errorMsg = errorData ? JSON.stringify(errorData) : error.message;
      console.error('Jira issue creation failed (v2). Body sent:', JSON.stringify(body, null, 2));
      console.error('Jira API Error Response:', errorMsg);
      throw new Error(`Jira API Error: ${errorMsg}`);
    }
  }

  /**
   * Test Jira connection and credentials
   * @param {Object} config - Jira configuration
   * @returns {Promise<Object>} Test result
   */
  async testConnection(config) {
    const domain = config.jiraDomain.replace(/\/$/, '').replace(/^https?:\/\//, '');
    const url = `https://${domain}/rest/api/3/myself`;
    const auth = Buffer.from(`${config.jiraEmail}:${config.jiraApiToken}`).toString('base64');

    try {
      const response = await axios.get(url, {
        headers: {
          'Authorization': `Basic ${auth}`,
          'Accept': 'application/json'
        }
      });
      return { success: true, user: response.data.displayName };
    } catch (error) {
      const errorMsg = error.response ? JSON.stringify(error.response.data) : error.message;
      return { success: false, error: errorMsg };
    }
  }

  /**
   * Convert plain text and metadata to Atlassian Document Format (ADF)
   */
  formatADF(task, sourceQuote, meetingId) {
    const content = [
      {
        type: 'paragraph',
        content: [{ type: 'text', text: 'This task was automatically generated by EchoNote.' }]
      }
    ];

    if (sourceQuote && typeof sourceQuote === 'string' && sourceQuote.trim()) {
      content.push({
        type: 'paragraph',
        content: [{ type: 'text', text: 'Transcript Context:', marks: [{ type: 'strong' }] }]
      });
      content.push({
        type: 'blockquote',
        content: [{
          type: 'paragraph',
          content: [{ 
            type: 'text', 
            text: sourceQuote.substring(0, 1000).replace(/[\u0000-\u001F\u007F-\u009F]/g, ""), 
            marks: [{ type: 'italic' }] 
          }]
        }]
      });
    }

    const meetingUrl = `${process.env.FRONTEND_URL || 'http://localhost:3000'}/meeting/${meetingId}`;

    content.push({
      type: 'paragraph',
      content: [
        { type: 'text', text: 'View meeting details in EchoNote: ' },
        { 
          type: 'text', 
          text: 'Open Meeting', 
          marks: [{ 
            type: 'link', 
            attrs: { href: meetingUrl } 
          }] 
        }
      ]
    });

    return {
      type: 'doc',
      version: 1,
      content
    };
  }

  /**
   * Map EchoNote priority to Jira priority names
   */
  mapPriority(priority) {
    const p = String(priority).toLowerCase();
    switch (p) {
      case 'high': return 'High';
      case 'medium': return 'Medium';
      case 'low': return 'Low';
      default: return 'Medium';
    }
  }
}

module.exports = new JiraService();
